
CREATE TABLE IF NOT EXISTS TRANSACTION
 (
     "TRANSACTION_ID" bigint auto_increment NOT NULL PRIMARY KEY,
     "USERID"  NUMBER(10,0) NOT NULL,
     "BOUGHT_TOKEN" VARCHAR2(20) NOT NULL,
     "BOUGHT_QUANTITY" NUMBER(10,6),
     "SOLD_TOKEN" VARCHAR2(20) NOT NULL,
     "SOLD_QUANTITY" NUMBER(10,6),
     "STATUS" VARCHAR2(20) NOT NULL,
     "EXECUTION_DATE" DATE ,
     "SETTLEMENT_DATE" DATE
 );

CREATE TABLE IF NOT EXISTS USERDETAIL
 (
     "ID"  INTEGER auto_increment NOT NULL ,
     "USER_ID"  INTEGER NOT NULL,
     "TOKEN" VARCHAR2(20) NOT NULL,
     "QUANTITY" NUMBER(10,6),
      UNIQUE KEY unique_key ("USER_ID","TOKEN")
 );



